baseURL = '/'
languageCode = 'zh-CN'
title = 'AI 知识库'
theme = 'ai-blog-theme'

[params]
  description = '探索人工智能、机器学习、深度学习和前沿技术的知识海洋'
  theme = 'light'
  accent_color = '#2563eb'
  enable_search = true
  enable_dark_mode = true
  enable_syntax_highlighting = true
  
  [[params.social]]
    name = 'GitHub'
    url = 'https://github.com'
    icon = 'github'
  
  [[params.social]]
    name = 'Twitter'
    url = 'https://twitter.com'
    icon = 'twitter'

[menu]
  [[menu.main]]
    identifier = 'posts'
    name = '文章'
    url = '/posts/'
    weight = 1

  [[menu.main]]
    identifier = 'about'
    name = '关于'
    url = '/about/'
    weight = 2
